name: "Create Release"

on: 
  push:
    tags:
    - '*'

jobs:

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz"
        bodyFile: "release-notes.md"